name = "big_binary"
defaultTargets = ["big_binary"]

[[lean_exe]]
name = "big_binary"
root = "Main"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.10.0"
